# Generated by Django 3.2.5 on 2021-11-05 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Semaforo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('latitud', models.FloatField(verbose_name='Latitud')),
                ('longitud', models.FloatField(verbose_name='Longitud')),
            ],
        ),
        migrations.CreateModel(
            name='Simulacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='FlujoVehicular',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(choices=[('FN', 'Nulo'), ('FB', 'Bajo'), ('FM', 'Medio'), ('FA', 'Alto')], default='FN', max_length=2)),
                ('imagen_captada', models.URLField(null=True, verbose_name='URL_Imagen')),
                ('semaforo', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='trafico.semaforo')),
                ('simulacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trafico.simulacion')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoSemaforo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('semaforo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trafico.semaforo')),
            ],
        ),
    ]
