# Generated by Django 3.2.5 on 2021-11-05 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trafico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flujovehicular',
            name='semaforo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='trafico.semaforo'),
        ),
    ]
