# Generated by Django 3.2.5 on 2021-11-05 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trafico', '0002_alter_flujovehicular_semaforo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='simulacion',
            options={'verbose_name': 'Simulacion', 'verbose_name_plural': 'Simulaciones'},
        ),
    ]
