# Generated by Django 3.2.5 on 2021-11-06 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trafico', '0003_alter_simulacion_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flujovehicular',
            name='descripcion',
            field=models.CharField(choices=[('Nulo', 'Nulo'), ('Bajo', 'Bajo'), ('Medio', 'Medio'), ('Alto', 'Alto')], default='Nulo', max_length=5),
        ),
    ]
