# Generated by Django 3.2.5 on 2021-11-07 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trafico', '0004_alter_flujovehicular_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadosemaforo',
            name='simulacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trafico.simulacion'),
        ),
    ]
