# Generated by Django 3.2.5 on 2021-11-07 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trafico', '0005_estadosemaforo_simulacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadosemaforo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
